# Generated by Django 4.1.2 on 2022-12-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expiry',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
