# Generated by Django 4.1.2 on 2022-12-06 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_authtoken_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
