# Generated by Django 4.1.2 on 2023-12-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isDeleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("mdi_icon", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Social",
                "verbose_name_plural": "Socials",
                "db_table": "social",
            },
        ),
    ]
