# Generated by Django 4.1.2 on 2023-12-17 21:36

import apps.info.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0002_social_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isDeleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.info.models.app_directory_path,
                    ),
                ),
            ],
            options={
                "verbose_name": "App",
                "db_table": "app_info",
            },
        ),
    ]
