# Generated by Django 4.1.2 on 2023-12-23 09:19

import apps.info.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0005_contactinformation_mailinginformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isDeleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("heading", models.CharField(max_length=255)),
                ("caption", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(upload_to=apps.info.models.banner_directory_path),
                ),
            ],
            options={
                "verbose_name": "Banner Item",
                "verbose_name_plural": "Banner Items",
                "db_table": "banner_item",
            },
        ),
    ]
