# Generated by Django 4.1.2 on 2023-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0006_banneritem"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isDeleted", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("statement", models.CharField(max_length=1000)),
            ],
            options={
                "verbose_name": "Banner Notification",
                "verbose_name_plural": "Banner Notifications",
                "db_table": "banner-notification",
            },
        ),
    ]
