# Generated by Django 4.1.2 on 2023-12-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("SENT", "sent"),
                            ("FAILED", "failed"),
                            ("RETRY", "retry"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Status",
                "verbose_name_plural": "Email Statuses",
                "db_table": "email-status",
            },
        ),
    ]
