# Generated by Django 4.1.2 on 2022-12-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_products_remove_orders_stripe_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
