# Generated by Django 4.1.2 on 2023-12-07 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_rename_orderitem_orderitems_alter_orders_email"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="orderitems",
            table="order-items",
        ),
        migrations.AlterModelTable(
            name="orders",
            table="orders",
        ),
    ]
