# Generated by Django 4.1.2 on 2023-12-08 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_customer_order_alter_orderitems_order_delete_orders"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitems",
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
    ]
