# Generated by Django 4.1.2 on 2023-12-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_payment_methods"),
        ("orders", "0007_alter_orderitems_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.paymentmethod",
            ),
        ),
    ]
