# Generated by Django 4.1.2 on 2023-12-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_payment_methods"),
        ("orders", "0008_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payment.paymentmethod"
            ),
        ),
    ]
