# Generated by Django 4.1.2 on 2023-12-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_alter_order_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPED", "Shipped"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED", "Returned"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Status",
                "verbose_name_plural": "Delivery Statuses",
                "db_table": "delivery-status",
            },
        ),
    ]
