# Generated by Django 4.1.2 on 2023-12-13 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_delivery_status_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.deliverystatus",
            ),
        ),
    ]
